export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  ADJUST_ITEM_QUANTITY: "ADJUST_ITEM_QUANTITY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
};
